project_name: my_photo_album_3
structure:
  my_photo_album_3:
    type: directory
    comment: '#ğŸ‘ˆ í”„ë¡œì íŠ¸ í´ë”'
    children:
    - name: config
      type: directory
      comment: '# ğŸ‘ˆ êµ¬ì„± íŒŒì¼ í´ë”'
      children:
      - name: .my_config.yaml
        type: file
        comment: '# ğŸ‘ˆ ì‚¬ìš©ì ì„¤ì • íŒŒì¼'
    - name: dataset
      type: directory
      comment: '# ğŸ‘ˆ ë°ì´í„° í´ë” - ì›ë³´ë‹ˆë¯¸ì§€ì— ëŒ€í•œ ì²˜ë¦¬ì •ë³´'
      children:
      - name: raw_image_dir
        type: file
        comment: '# ğŸ‘ˆ ì›ë³¸ ì´ë¯¸ì§€ (ë¼ë²¨ ì—†ìŒ)'
      - name: raw_jsons_dir
        type: file
        comment: '# ğŸ‘ˆ ì›ë³¸ ì´ë¯¸ì§€ì˜ ë¼ë²¨ íŒŒì¼'
      - name: detected_list_path
        type: file
        comment: '# ğŸ‘ˆ ëª©ì ëŒ€ìƒì´ ê²€ì¶œëœ ì›ë³¸ ì´ë¯¸ì§€ ëª©ë¡'
      - name: undetect_list_path
        type: file
        comment: '# ğŸ‘ˆ ëª©ì ëŒ€ìƒì´ ê²€ì¶œë˜ì§€ì•Šì€ ì›ë³¸ ì´ë¯¸ì§€ ëª©ë¡'
      - name: fail_list
        type: directory
        comment: '# ğŸ‘ˆ ì¼ê¸°ì¤‘ ì‹¤íŒ¨í•œ ì›ë³¸ ì´ë¯¸ì§€ ëª©ë¡'
        children: []
    - name: src
      type: directory
      comment: '# ğŸ‘ˆ ì†ŒìŠ¤ ì½”ë“œ í´ë”'
      children:
      - name: face_indexer_landmark.py
        type: file
        comment: '# ğŸ‘ˆ ì–¼êµ´ ì¸ë±ì‹± (MediaPipe ê¸°ë°˜)'
      - name: face_search_web.py
        type: file
        comment: '# ğŸ‘ˆ ê²€ìƒ‰ ì›¹ì„œë²„ (FastAPI)'
      - name: config_loader.py
        type: file
        comment: '# ğŸ‘ˆ YAML êµ¬ì„± ë¡œë”'
      - name: face_detector.py
        type: file
        comment: '# ğŸ‘ˆ ì–¼êµ´ ê²€ì¶œ + í•´ì‹œ + JSON ìƒì„± ë¼ì´ë¸ŒëŸ¬ë¦¬'
      - name: (face_reviewer.py)
        type: file
        comment: '# ğŸ‘ˆ (ì˜ˆì •) ë¼ë²¨ë§ UI'
    - name: output
      type: directory
      comment: '# ğŸ‘ˆ ê²°ê³¼ í´ë”'
      children:
      - name: deceted_faces
        type: directory
        comment: '# ğŸ‘ˆ ê²€ì¶œëœ ëª©ì (ì–¼êµ´) ì´ë¯¸ì§€ (ì¸ë±ì‹±ìš©)'
        children: []
      - name: face_index.pkl
        type: file
        comment: '# ğŸ‘ˆ ì–¼êµ´ ì¸ë±ì‹± ê²°ê³¼ (embedding í¬í•¨)'
      - name: results
        type: directory
        comment: '# ğŸ‘ˆ ê²€ìƒ‰ ê²°ê³¼ ì´ë¯¸ì§€ ì‹œê°í™” ë° index plot'
        children: []
      - name: work_logs
        type: directory
        comment: '# ğŸ‘ˆ ì‘ì—… ê³¼ì • ì´ë ¥ì„ ê¸°ë¡'
        children: []
    - name: templates
      type: directory
      comment: '# ğŸ‘ˆ UI í…œí”Œë¦¿'
      children:
      - name: search.html
        type: file
        comment: '# ğŸ‘ˆ ê²€ìƒ‰ UI í…œí”Œë¦¿'
    - name: pyproject.toml
      type: file
      comment: '# ğŸ‘ˆ Poetry ì„¤ì •'
    - name: requirements.txt
      type: file
      comment: '# ğŸ‘ˆ Pip ì„¤ì •'
    - name: my_photo_album_3.txt
      type: file
      comment: '# ğŸ‘ˆ í”„ë¡œì íŠ¸ ë”í† ë¦¬ êµ¬ì„±í¬'
    - name: README.md
      type: file
      comment: '# ğŸ‘ˆ í”„ë¡œì íŠ¸ ì„¤ëª…ì„œ'
    - name: LICENSE
      type: file
      comment: '# ğŸ‘ˆ í”„ë¡œì íŠ¸ ë¼ì´ì„¼ìŠ¤'
